version: '2'
services:
  db:
    container_name: db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
      - back-tier
    ports: 
      - 127.0.0.1:3306:3306
  web:
    container_name: web
    build:
      context: .
    networks:
      - back-tier
    volumes:
      - .:/var/www/html
    ports:
      - 127.0.0.1:80:80
networks:
  back-tier:
    driver: bridge
    
