version: '2'
services:
  db:
    container_name: db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testable_code_workshop
    networks:
      - back-tier
    ports: 
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/
  web:
    container_name: web
    build:
      context: .
    networks:
      - back-tier
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
networks:
  back-tier:
    driver: bridge
    
