# app/config/routing.yml
reviews_get:
    path:     /reviews/{id}
    defaults: { _controller: review_controller:getAction }
    methods: [GET]
reviews_post:
    path:     /reviews
    defaults: { _controller: review_controller:postAction }
    methods: [POST]
reviews_put:
    path:     /reviews/{id}
    defaults: { _controller: review_controller:putAction }
    methods: [PUT]
company_get:
    path:     '/company'
    defaults: { _controller: company_controller:getAction }
    methods: [GET]